<?php

/*
 *   strong 2014.08.5
 *
 * 我们致力于为每一位用户, 打造独立个性的产品, 提升用户体验, 让你的网站更加的接近 Web 2.0 标准.
 *
 * QQ:  695023684
 * Email: 695023684@qq.com
 * Http://www.quuqu.com/demo

 *
 */
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}



//语言, 如修改注意标点符号

$lang = array(
	'home' => '首页',
	'forum' => '论坛',
	'pic' => '美图',
	'guide' => '导读',
	'news'=>'新闻',
	'mdoing' => '记录',
	'mfollow' => '广播',
	'mfriend' => '好友',
	'biaoqian' => '标签',
	'fanhuiluntan'=>'返回论坛',
	'fanhuibankuai'=>'返回板块',
	'gexingqianming'=>'个性签名',
	'pindao' => '频道',
	'jiazai' => '点击加载',
	'meiyoule' => '没有了',
	'guanbi'=> '关闭',
	'jiazaizhong' => '加载中',
	'mfriendall' => '全部',
	'zhutifenlei' => '分类',
	'gengduo' => '更多',
	'shouqi' => '收起',
	'mfriendol' => '在线好友',
	'mfriendbl' => '黑名单',
	'mfriendrq' => '好友请求',
	'mfriendprofile' => '资料',
	'mfriendgroup' => '分组',
	'mblog' => '日志',
	'mfeed' => '动态',
	'photo' => '相册',
	'more' => '更多',
	'fup' => '上级',
	'flist' => '列表',
	'plist' => '所在频道',
	'res' => '刷新',
	'prev' => '上一页',
	'next' => '下一页',
	'load' => '加载更多',
	'load_pic' => '拼命加载中...',
	'load_nopic' => '没有了怎么拌',
	'newth' => '新帖',
	'dfth' => '默认',
	'subfrm' => '子版块',
	'thtys' => '排序',
	'othtys' => '展开分类',
	'pta' => '发表于',
	'reply' => '发表回复',
	'srp' => '查看回复',
	'rcom' => '发表评论',
	'acom' => '查看评论',
	'opt' => '选填',
	'od' => '条',
	'de' => '的',
	'tt' => '共有',
	'jing'=>'精',
	'zhi'=>'置',
	'tu'=>'图',
	'thread' => '主题',
	'reply' => '回复',
	'views' => '看贴',
	'tietu' => '贴图',
	'mods' => '管理',
	'quxiao' => '取消',
	'nomessage' => '此贴无文字内容',
	'mthread' => '帖子',
	'mforum' => '版块',
	'profile' => '个人资料',
	'gerenzhongxin' => '个人中心',
	'fenxiang'=>'分享',
	'geren'=>'个人',
	'tuchuang' => '图床',
	'profilet' => '资料',
	'bankuaishoucang' => '板块收藏',
	'chakanxiaoxi' => '查看消息',
	'wodeshouchang'=>'我的收藏',
	'wodezhuti' => '我的主题',
	'favorite' => '收藏',
	'yishoucang'=>'已收藏',
	'mypm' => '我的消息',
	'psubject' => '帖子详情',
	'arc' => '文章',
	'lz' => '楼主',
	'kanlouzhu' => '只看楼主',
	'kanquanbu' => '看全部',
	'cldate' => '日期格式:2010-12-01 10:50',
	'pcf' => '重复',
	'back' => '返回',
	'search' => '搜索',
	'fatie' =>'发帖',
	'searchthread' => '输入帖子关键字',
	'searchportal' => '输入文章关键字',
	'4hr' => '4小时',
	'24hr' => '24小时',
	'168hr' => '一周',
	'720hr' => '一月',
	'new_remind' => '有新提醒',
	'new_mp'=>'new',
	'mefriend_doing' => '我和好友',
	'friend_feed' => '好友动态',
	'wenzhang' => '门户',
	'tupianqiang' => '图片瀑布流',
	'wodezhuti' => '我的主题',
	'zhutishouchang' => '主题收藏',
	'wenzhangshoucang' =>'文章收藏',
	'wodezilaio' => '我的资料',
	'wodexiaoxi' => '我的消息',
	'wodehaoyou' => '我的好友',
	'newjinghua' => '最新精华',
	'newhuifu' => '最新回复',
	'newfabu' => '最新发表',
	'qiangshafa' => '抢沙发',
	'dengru' => '登入',
	'qqdengru' => 'QQ登入',
	'dengruzhongxin' => '登入中心',
	'tuichu' => '退出',
	'zuixin' => '最新',
	'remen' => '热门',
	'retie' => '热帖',
	'newstie'=>'新帖',
	'jinghua' => '精华',
	'fabuyu' => '发布于',
	'touch' => '触屏版',
	'tthread' => '正文',
	'tzxiangqing' => '帖子详情',
	'butubukuai' => '不吐不快！',
	'kuaijie' => '快捷>>',
	'zhutil' => '主题：',
	'paimingl' => '排名：',
	'zhengxu' =>'正序浏览',
	'daoxu' => '倒序浏览',
	'loginaq' => '安全提问?',
	'nosearch' => '暂无',
	'gohome' => '返回首页',
	'regmes' => '原因',
	'upload_pic' => '上传图片',
	'reg' => '注册',
	'zhucezhongxin' =>'注册中心',
	'qq' => '登录',
	'noid' => '没有账号?',
	'yesid' => '已有账号?',
	'yuehot' => '本月热帖',
	'zhuohot' => '本周热帖',
	'shouchang' => '收藏排行',
	'paixu' => '排序',
	'hotforum' => '热门板块',
	'hottz' => '热门帖子',
	'username' => '账号',
	'biaozhunban'=>'标准版',
	'diannaoban'=>'电脑版',
	'jingcaituijian' => '精彩推荐',
	'zuixinfabu' =>'最新发布'

    );



?>